import { Router, type IRouter } from "express";
import { rateLimiter, requireAuth, requireAdmin } from "../middlewares/rateLimiter";
import healthRouter from "./health";
import authRouter from "./auth";
import llmConfigRouter from "./llm-config";
import llmProxyRouter from "./llm-proxy";
import chatRouter from "./chat";
import modelProfilesRouter from "./model-profiles";
import trainingDataRouter from "./training-data";
import ragRouter from "./rag";
import openclawRouter from "./openclaw";
import scanRouter from "./scan";
import vpsDatabaseRouter from "./vps-database";
import vpsTrainingRouter from "./vps-training";
import autoCollectorRouter from "./auto-collector";
import deepResearchRouter from "./deep-research";
import mediaRouter from "./media";
import backupRouter from "./backup";
import entTrainingRouter from "./ent-training";
import monitorRouter from "./monitor";
import modelEvolutionRouter from "./model-evolution";
import projectBrainRouter from "./project-brain";
import analyticsRouter from "./analytics";
import notificationsRouter from "./notifications";
import automationsRouter from "./automations";
import entEndoscopyDatasetsRouter from "./ent-endoscopy-datasets";
import llmTrainingPipelineRouter from "./llm-training-pipeline";
import entClinicalRouter from "./ent-clinical";
import socialMediaRouter from "./social-media";
import hedgeFundRouter from "./hedge-fund";
import dataAgentRouter from "./data-agent";
import voiceAgentRouter from "./voice-agent";
import pubmedEntCollectorRouter from "./pubmed-ent-collector";
import advancedTrainingRouter from "./advanced-training-pipeline";
import hedgeFundTrainingRouter from "./hedge-fund-training";
import signalsRouter from "./signals";
import dashboardKpisRouter from "./dashboard-kpis";
import hfAnalyticsRouter from "./hf-analytics";
import agentsStatusRouter from "./agents-status";
import marketProxyRouter from "./market-proxy";
import codeGuardianRouter from "./code-guardian";
import socialMediaPlatformRouter from "./social-media-platform";
import researchPipelineRouter from "./research-pipeline";
import platformApiRouter from "./platform-api";
import ragPipelineRouter from "./rag-pipeline";
import exportRouter from "./export";
import healthCheckRouter from "./health-check";
import evaluationRouter from "./evaluation";
import agentflowRouter from "./agentflow";
import promptsRouter from "./prompts";
import modelCompareRouter from "./model-compare";
import reportsRouter from "./reports";
import memoryRouter from "./memory";
import costsRouter from "./costs";
import teamRouter from "./team";
import complianceRouter from "./compliance";
import codeTerminalRouter from "./code-terminal";
import chatImportRouter from "./chat-import";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(llmConfigRouter);

router.use(rateLimiter(30, 60000), llmProxyRouter);
router.use(chatRouter);
router.use(modelProfilesRouter);

router.use(rateLimiter(60, 60000), trainingDataRouter);
router.use(ragRouter);
router.use(openclawRouter);
router.use(scanRouter);
router.use(vpsDatabaseRouter);
router.use(vpsTrainingRouter);
router.use(autoCollectorRouter);
router.use(rateLimiter(10, 60000), deepResearchRouter);
router.use(mediaRouter);
router.use(backupRouter);
router.use(entTrainingRouter);
router.use(monitorRouter);
router.use(modelEvolutionRouter);
router.use(projectBrainRouter);
router.use(analyticsRouter);
router.use(notificationsRouter);
router.use(automationsRouter);
router.use(entEndoscopyDatasetsRouter);
router.use(llmTrainingPipelineRouter);
router.use(entClinicalRouter);
router.use(socialMediaRouter);
router.use(hedgeFundRouter);
router.use(dataAgentRouter);
router.use(voiceAgentRouter);
router.use(pubmedEntCollectorRouter);
router.use(advancedTrainingRouter);
router.use(hedgeFundTrainingRouter);
router.use(signalsRouter);
router.use(dashboardKpisRouter);
router.use(hfAnalyticsRouter);
router.use(agentsStatusRouter);
router.use(marketProxyRouter);
router.use(codeGuardianRouter);
router.use(socialMediaPlatformRouter);
router.use(researchPipelineRouter);
router.use(platformApiRouter);
router.use(ragPipelineRouter);
router.use(exportRouter);
router.use(healthCheckRouter);
router.use(evaluationRouter);
router.use(agentflowRouter);
router.use(promptsRouter);
router.use(modelCompareRouter);
router.use(reportsRouter);
router.use(memoryRouter);
router.use(costsRouter);
router.use(teamRouter);
router.use(complianceRouter);
router.use("/code-terminal", requireAuth, codeTerminalRouter);
router.use(chatImportRouter);

export default router;
