import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import llmConfigRouter from "./llm-config";
import llmProxyRouter from "./llm-proxy";
import chatRouter from "./chat";
import modelProfilesRouter from "./model-profiles";
import trainingDataRouter from "./training-data";
import ragRouter from "./rag";
import openclawRouter from "./openclaw";
import scanRouter from "./scan";
import vpsDatabaseRouter from "./vps-database";
import vpsTrainingRouter from "./vps-training";
import autoCollectorRouter from "./auto-collector";
import deepResearchRouter from "./deep-research";
import mediaRouter from "./media";
import backupRouter from "./backup";
import entTrainingRouter from "./ent-training";
import monitorRouter from "./monitor";
import modelEvolutionRouter from "./model-evolution";
import projectBrainRouter from "./project-brain";
import analyticsRouter from "./analytics";
import notificationsRouter from "./notifications";
import automationsRouter from "./automations";
import entEndoscopyDatasetsRouter from "./ent-endoscopy-datasets";
import llmTrainingPipelineRouter from "./llm-training-pipeline";
import entClinicalRouter from "./ent-clinical";
import socialMediaRouter from "./social-media";
import hedgeFundRouter from "./hedge-fund";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(llmConfigRouter);
router.use(llmProxyRouter);
router.use(chatRouter);
router.use(modelProfilesRouter);
router.use(trainingDataRouter);
router.use(ragRouter);
router.use(openclawRouter);
router.use(scanRouter);
router.use(vpsDatabaseRouter);
router.use(vpsTrainingRouter);
router.use(autoCollectorRouter);
router.use(deepResearchRouter);
router.use(mediaRouter);
router.use(backupRouter);
router.use(entTrainingRouter);
router.use(monitorRouter);
router.use(modelEvolutionRouter);
router.use(projectBrainRouter);
router.use(analyticsRouter);
router.use(notificationsRouter);
router.use(automationsRouter);
router.use(entEndoscopyDatasetsRouter);
router.use(llmTrainingPipelineRouter);
router.use(entClinicalRouter);
router.use(socialMediaRouter);
router.use(hedgeFundRouter);

export default router;
